### ISSUE TITLE
Lantern always lit, Chrome 70+

### ISSUE THREAD

**Issue by CacheMinimal** [newfolder0/chrome-clacks#11]
Although I would love to think that Terry's legacy has spread to the entire Internet, I suspect the more likely truth is that Google have changed the API for extensions since Chrome 70!  Regardless of the site visited the lantern now lights.

I am now running Chrome 71.0.3578.80 on 64-bit Linux but this issue has been present on all platforms since the release of Chrome 70.

Please let me know if I can assist with any other debug information?

Thanks in advance,

Ian.

**Comment by java-artisan** [comment]
Same for me. Also 64bit Linux, running Chromium 72.0.3626.119.

Anything I can do to help ?

**Comment by newfolder0** [comment]
Thank you for the feedback and I am glad to know I am not the only person still using this extension, even after all of this time!

I am sorry to say that at the moment I don't have time to look into this, though I have noticed the same problem on my computer as well.

If anyone else can look at it and suggest a bug fix, I would be grateful! Otherwise I will look at it whenever I find the time (unfortunately no guarantees on how soon). Apologies.

**Comment by SamuelCook** [comment]
https://github.com/newfolder0/chrome-clacks/pull/12 should resolve this issue.

**Comment by nhitze** [comment]
I merged your PR @SamuelCook into my Fork since @newfolder0 doesn't seem to have the time for it.

https://github.com/nhitze/chrome-clacks

**Comment by newfolder0** [comment]
I am really sorry about this.

Honestly, I am now outside the software world and haven't touched Javascript for >4 years. I haven't written any serious code or even used git in >1.5 years.

I will have some time off before Christmas and I'll try to sort this out... but long term, I would honestly be pretty happy to allow one of you to maintain the extension. It's obvious that I'm not the person for the job right now.... For security purposes though, I would not be willing to allow someone I did not know personally to approve updates to a browser extension that could potentially affect a few thousand users, who have placed their trust in me by installing it. So we have a problem. I'll think about a solution.

I haven't even read your suggested changes yet, or thought about how simple and innocuous they might be... but I am very unwilling to push any updates out that I haven't done full due diligence on. Just for security purposes. Browsers are a minefield.

In any case, I'll get back to GitHub, check your pull requests and hopefully accept them then push the update to the web store before Christmas. Worst case, end of January. Sorry guys. I really appreciate your patience and the politeness of nhitze's comment. Thanks for forking it in the meantime!

**Comment by moorobaiken** [comment]
@newfolder0 if you want a maintainer, i don't mind helping out

**Comment by newfolder0** [comment]
I've finally merged the request and uploaded the updated version to the Google Chrome Web Store.

Sorry for the ridiculous delay everyone, thanks for your patience.

That's quite generous of you, @moorobaiken, and honestly I'd love to accept your offer. Because of the (frankly ridiculous) level of permissions required by this extension, I'm not willing to share maintenance of the Web Store version with anyone I don't know personally.

What would you suggest? Now that I think about it, you and others could give your approval for merge requests, which won't be merged into the main branch until I accept them but it helps to give me confidence that they have been vetted by multiple people. I didn't realise this was a thing before today (as I said, I haven't touched software or GitHub for a few years now).

In the end, it of course didn't take me much time to review the changes and be sure they were safe. It was only a few lines. So maybe I just need to be a more responsible developer and actually prioritise making time for this. ;)

Cheers, all and have a lovely Christmas! (if you celebrate that, of course)
