### ISSUE TITLE
Improvement for background.js

### ISSUE THREAD

**Issue by Ryuno-Ki** [newfolder0/chrome-clacks#3]
First things first: Thank you.

Since I'm not a Chrome user, I'll just share my thoughts about some bits of your code.
1. https://github.com/newfolder0/chrome-clacks/blob/03020050e7107bce48aaf8604bc7f5f7a153d194/src/background.js#L21
   The variable does not describe a match, but a pattern.
2. https://github.com/newfolder0/chrome-clacks/blob/03020050e7107bce48aaf8604bc7f5f7a153d194/src/background.js#L29
   You may can solve this with a [ternary operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator).
3. https://github.com/newfolder0/chrome-clacks/blob/03020050e7107bce48aaf8604bc7f5f7a153d194/src/background.js#L39
   In case you're just about to merge an Array here, why don't use [Array.prototype.join()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/join)?
4. https://github.com/newfolder0/chrome-clacks/blob/03020050e7107bce48aaf8604bc7f5f7a153d194/src/background.js#L69
   Since there is only one expression, why don't merge the if condition via `&&`? (`else if` will take care of handling the else-branch).

**Comment by newfolder0** [comment]
Thanks for the input :).

1.You're not a match, but a pattern. Take that (alright then, I'll change it). I originally called it 'expression' but that seemed too generic.
1. I'm working backwards (nope, I don't know why either), see number 3.
2. Hmm, newClacks is actually an array of objects so newClacks.join("\n") doesn't work right out of the box. Here: http://stackoverflow.com/questions/16607557/javascript-perform-join-on-value-in-object-array are a lot of different suggestions but I don't think any of them are really better. They all require confusing one-liners or extra libraries and I think a straightforward for loop is just easier to read in this case. Actually scratch all of that, it was just fixed by the guy sitting next to me, now it looks like this: http://pastebin.com/ejG13tBw
3. True, I think that was originally there for readability but I like your suggestion. Done!
