### ISSUE TITLE
Detect X-Clacks-Overhead in meta tags

### ISSUE THREAD

**Issue by nickcernis** [newfolder0/chrome-clacks#6]
Some site owners are adding the clacks header using a meta tag in their HTML:

`<meta http-equiv="X-Clacks-Overhead" content="GNU Terry Pratchett" />`

(As suggested at http://www.gnuterrypratchett.com/#HTML )

It would be great if the plugin also recognised pages containing meta tags with an http-equiv attribute of 'X-Clacks-Overhead' and 'Clacks-Overhead', and not just HTTP headers.

**Comment by newfolder0** [comment]
Sounds good, I'll have a look into it! Suggestions are welcome if you know anything relevant :).

**Comment by Rob-bb** [comment]
I have added the following to virtual hosts:

```
<IfModule headers_module>
    # https://www.reddit.com/r/discworld/comments/2yt9j6/gnu_terry_pratchett/
    header set X-Clacks-Overhead "GNU Terry Pratchett"
</IfModule>
```

but it seems the icon is intermittent.  Sometimes it will flash briefly and vanish but reloading the page will show it properly.  

Link to images:  
http://thks.great-ape.co.nz/clacks/no-show.png
http://thks.great-ape.co.nz/clacks/show.png

cheers, and thanks.  This is a cool thing to do for the old boy.

**Comment by newfolder0** [comment]
I've change a few things and now it should recognise meta tags in the content.js script, which are passed back to background.js - I had a bit of trouble making them persist properly on complicated page loads with different elements loading after one another. It seems to work reliably now.

**Comment by nickcernis** [comment]
Wonderful! I've tested the latest version in the Chrome store and meta tag detection is working great for me.

I've updated the description of the GNU Terry Pratchett WordPress plugin to give your extension a mention: https://wordpress.org/plugins/gnu-terry-pratchett/

Thanks for all your hard work with this – you've done a great job!

**Comment by Rob-bb** [comment]
It seems to work more reliably in windows chrome than linux chrome.  The page in question uses an I frame to load another page from the same site (embedding a php forum in the main page) which might be the issue but I don't have enough knowledge about how the plugins work to know how to help you.

If you think of anything I can to to give you more info le me know.

thanks

**Comment by newfolder0** [comment]
Aaaaaand I've learnt a valuable lesson. Adding the content script to detect the meta tags increased the level of permissions required and the complaints are rolling in. Oh the feedback. Also, after uploading this update to the Chrome Web Store, the number of 'weekly users' has nearly halved. I assume that's because Chrome disables an extension that asks for new permissions in an update until the user specifically enables it again. That isn't a problem (if slightly disappointing) but it will certainly make me think twice about changes like that in the future. I wonder if there's a way of allowing people to revoke certain permissions and disable certain functionality?

Anyway, to your problem rob-bb... I'll try it out on my linux machine tomorrow, so far I've been testing it on OSX (yes, I know). Someone else has given similar feedback about the clacks on their WordPress site not being detected after the latest update. The webNavigation.onCommitted listener (in background.js) ignores 'auto_subframe' transitions, which I thought should include stuff loaded in iframes. I'd be interested to know the specific website in question if you're happy to share it, you can email me at devpete0@gmail.com if you'd rather keep it private.

nickcernis, have you had any trouble with WordPress pages?

It's lovely to hear from people who appreciate it, I'm enjoying this little project but the feedback about the permissions hasn't been fantastic. I really wish there was a way to transparently publish updates from Github to the Chrome Web Store, as it stands the users really don't have any guarantee that I'm not modifying it maliciously in the middle. As usual, if anyone else has any bright ideas I'd love to hear them :).

**Comment by newfolder0** [comment]
I forgot to add, thanks a lot for the help guys! That was rude. I really, really appreciate it! :)

**Comment by Rob-bb** [comment]
It's all good. It seems sorted now, site if you want is http://thks.great-ape.co.nz/

What used to happen happened after you clicked on the forum link and then went back to the main page.

cheers,

PS:  I did a double take at the permissions also.  It does seem excessive.

**Comment by newfolder0** [comment]
Ah, good to hear. I'm working on making the permissions optional (along with HTML meta tag functionality) but I haven't managed to make it work yet and I can only work on this outside of work hours!

It is completely reasonable that people are complaining about the permissions, I would probably uninstall an extension like this if it asked for that... but then again I was kind of surprised by how many people accepted the original permissions so I guess I got complacent. Lesson learnt.

**Comment by newfolder0** [comment]
Interesting update on this (same response I've posted on reddit)... After making the permission I _thought_ was causing the problems optional, the extension was still asking for permission to "read and change all the data on all the websites you visit". That was a bit frustrating, so I reverted to an old version (1.0, the very first that was on the Chrome Web Store) and it also asks for the same thing.
Either I'm doing something very wrong and am confused, or:
I think it's possible that it was always asking in those words and everyone just accepted it. When I updated it to find HTML meta tags, I added new permissions in the manifest and the _change_ triggered Chrome to prompt the user to accept them... but that level of permissions made exactly the same request, in the same words, again. I might still be wrong, but this is how it looks to me now. I hope that makes sense.

Maybe I wasn't so wrong to get complacent about a lot of people accepting whatever you ask but it only applies to the initial installation!

**Comment by nickcernis** [comment]
Sorry to hear that the permissions issues gave you some trouble!

I wouldn't worry too much about a few grumbles over permissions – it's quite normal in the Chrome Store, from what I've seen. Your reviews seem very positive, and a lot of folks are grateful for all of your hard work.

If you still see complaints, you could always add a short notice to the top of the plugin description:

> This plugin asks for the minimum permissions needed to detect the Clacks meta tag and HTTP header. It does not read or store any private data. The full source is available on GitHub: https://github.com/newfolder0/chrome-clacks/

That may reassure more privacy-conscious users who skim the description. Tech-savvy users can always view the source on GitHub, or use the [CRX Extension](https://chrome.google.com/webstore/detail/chrome-extension-source-v/jifpbeccnghkjeaalbbjmodiffmgedin?hl=en) to scan the code from the Chrome Store app page directly.

I haven't seen any privacy notices that scare me, and it's working great everywhere I've tested it. Thanks again for your efforts!

**Comment by newfolder0** [comment]
I'm afraid I forgot to reply to this earlier. Once everything kind of stabilised I was a bit sick of it so I left it at that for a while :). Thanks for the input and friendly words, I've just updated the description to include what you suggested!
